;;********************** U-colors.lisp *****************************
;;
;;
#|ListWorks Colors ---------------------------------------- 
 AZURE1
 CADETBLUE1
 CADETBLUE2
 CADETBLUE3
 CADETBLUE4
 CORAL
 CORNFLOWERBLUE
 DARKORANGE
 DARKORANGE1
 DARKORANGE2
 DARKORCHID1
 DARKORCHID2
 DARKSLATEBLUE
 DEEPPINK
 GRAY21
 GRAY22
 GRAY23
 GRAY24
 GRAY25
 GRAY54
 GRAY55
 GRAY56
 GRAY57
 GRAY58
 GRAY59
 GRAY88
 GRAY89
 GRAY90
 GRAY91
 GRAY92
 GRAY93
 GREY20
 GREY21
 GREY22
 GREY23
 GREY24
 GREY25
 GREY54
 GREY55
 GREY56
 GREY57
 GREY58
 GREY59
 GREY87
 GREY88
 GREY89
 GREY90
 GREY91
 GREY92
 HONEYDEW3
 HONEYDEW4
 HOTPINK
 KHAKI4
 LAVENDERBLUSH1
 LAVENDERBLUSH2
 LAVENDERBLUSH3
 LAVENDERBLUSH4
 LIGHTCORAL
 LIGHTCYAN4
 LIGHTGOLDENROD1
 LIGHTGOLDENROD2
 LIGHTGOLDENROD3
 LIGHTGOLDENROD4
 LIGHTPINK
 LIGHTSALMON
 LIGHTSALMON1
 LIGHTSALMON2
 LIGHTSALMON3
 LIGHTSALMON4
 LIGHTSLATEBLUE
 LIGHTYELLOW1
 LIGHTYELLOW2
 LIGHTYELLOW3
 LIGHTYELLOW4
 MAGENTA
 MEDIUMBLUE
 MEDIUMORCHID1
 MEDIUMORCHID2
 MEDIUMORCHID3
 MEDIUMORCHID4
 MEDIUMSLATEBLUE
 MIDNIGHTBLUE
 MISTYROSE1
 MISTYROSE2
 MISTYROSE3
 MISTYROSE4
 NAVY
 NAVYBLUE
 ORANGE
 ORANGE1
 ORANGE2
 ORANGE3
 ORANGE4
 ORANGERED
 PALETURQUOISE1
 PALETURQUOISE2
 PALETURQUOISE3
 PALETURQUOISE4
 PINK
 PLUM1
 PLUM2
 PLUM3
 PLUM4
 ROSYBROWN
 ROYALBLUE
 SALMON3
 SALMON4
 SLATEBLUE
 TOMATO
 TURQUOISE1
 YELLOW1
 YELLOW2
 AQUAMARINE1
 AQUAMARINE2
 AZURE2
 AZURE3
 AZURE4
 BLUE
 BLUE1
 BLUE2
 BLUEVIOLET
 CORAL1
 CORAL2
 CORAL3
 CORAL4
 CYAN1
 CYAN2
 CYAN3
 CYAN4
 DARKGOLDENROD1
 DARKGOLDENROD2
 DARKORANGE4
 DARKORCHID
 DARKORCHID3
 DARKORCHID4
 DARKSLATEGRAY1
 DARKSLATEGRAY2
 DARKSLATEGRAY3
 DARKSLATEGRAY4
 DARKTURQUOISE
 DARKVIOLET
 DEEPSKYBLUE
 DODGERBLUE
 FIREBRICK
 GOLD1
 GOLD2
 GOLD3
 GOLD4
 GOLDENROD1
 GOLDENROD2
 GOLDENROD3
 GOLDENROD4
 GRAY100
 GRAY26
 GRAY27
 GRAY28
 GRAY29
 GRAY30
 GRAY31
 GRAY32
 GRAY60
 GRAY61
 GRAY62
 GRAY63
 GRAY64
 GRAY65
 GRAY66
 GRAY94
 GRAY95
 GRAY96
 GRAY97
 GRAY98
 GRAY99
 GREY26
 GREY27
 GREY28
 GREY29
 GREY30
 GREY31
 GREY32
 GREY60
 GREY61
 GREY62
 GREY63
 GREY64
 GREY65
 GREY66
 GREY93
 GREY94
 GREY95
 GREY96
 GREY97
 GREY98
 GREY99
 LIGHTBLUE
 LIGHTSKYBLUE
 LIGHTSTEELBLUE
 MAROON
 MEDIUMORCHID
 MEDIUMPURPLE
 MEDIUMPURPLE1
 MEDIUMPURPLE2
 MEDIUMPURPLE3
 MEDIUMPURPLE4
 MEDIUMTURQUOISE
 MEDIUMVIOLETRED
 ORANGERED1
 ORANGERED2
 ORANGERED3
 ORANGERED4
 PALETURQUOISE
 PALEVIOLETRED
 PLUM
 POWDERBLUE
 PURPLE
 PURPLE1
 PURPLE2
 PURPLE3
 PURPLE4
 ROYALBLUE1
 ROYALBLUE2
 ROYALBLUE3
 ROYALBLUE4
 SKYBLUE
 SLATEBLUE1
 SLATEBLUE2
 SLATEBLUE3
 SLATEBLUE4
 SNOW1
 STEELBLUE
 THISTLE
 THISTLE1
 THISTLE2
 THISTLE3
 TOMATO1
 TOMATO2
 TOMATO3
 TOMATO4
 TURQUOISE
 TURQUOISE2
 TURQUOISE3
 TURQUOISE4
 VIOLET
 VIOLETRED
 YELLOW3
 YELLOW4
 ANTIQUEWHITE
 ANTIQUEWHITE1
 ANTIQUEWHITE2
 ANTIQUEWHITE3
 ANTIQUEWHITE4
 AQUAMARINE
 AQUAMARINE3
 AQUAMARINE4
 BISQUE
 BISQUE1
 BISQUE2
 BLANCHEDALMOND
 BLUE3
 BLUE4
 CADETBLUE
 CHARTREUSE
 CYAN
 DARK-BLUE
 DARKGOLDENROD
 DARKGOLDENROD3
 DARKGOLDENROD4
 DARKGREEN
 DARKOLIVEGREEN
 DARKSEAGREEN
 DARKSEAGREEN1
 DARKSEAGREEN2
 DARKSEAGREEN3
 DARKSEAGREEN4
 DEEPPINK1
 DEEPPINK2
 DEEPPINK3
 DEEPPINK4
 DEEPSKYBLUE1
 DEEPSKYBLUE2
 DEEPSKYBLUE3
 DODGERBLUE1
 DODGERBLUE2
 DODGERBLUE3
 DODGERBLUE4
 FLORALWHITE
 FORESTGREEN
 GAINSBORO
 GHOSTWHITE
 GRAY-BLUE
 GRAY0
 GRAY1
 GRAY3
 GRAY33
 GRAY34
 GRAY35
 GRAY36
 GRAY37
 GRAY38
 GRAY39
 GRAY4
 GRAY40
 GRAY5
 GRAY6
 GRAY67
 GRAY68
 GRAY69
 GRAY70
 GRAY71
 GRAY72
 GRAY73
 GRAY74
 GREY0
 GREY1
 GREY100
 GREY2
 GREY3
 GREY33
 GREY34
 GREY35
 GREY36
 GREY37
 GREY38
 GREY39
 GREY4
 GREY5
 GREY6
 GREY67
 GREY68
 GREY69
 GREY70
 GREY71
 GREY72
 GREY73
 HIGHLIGHT-RED
 HOTPINK1
 HOTPINK2
 HOTPINK3
 HOTPINK4
 INDIANRED1
 INDIANRED2
 INDIANRED3
 INDIANRED4
 LAWNGREEN
 LIGHT-BLUE
 LIGHT-BROWN
 LIGHT-RED
 LIGHTCYAN
 LIGHTSEAGREEN
 LINEN
 LISPWORKS-BLUE
 MEDIUM-BLUE
 MEDIUM-BROWN
 MEDIUM-GREEN
 MEDIUM-YELLOW
 MEDIUMAQUAMARINE
 MEDIUMSEAGREEN
 NAVAJOWHITE
 OLDLACE
 ORCHID
 PALEGREEN
 PALEGREEN1
 PALEGREEN2
 PALEGREEN3
 PAPAYAWHIP
 PEACHPUFF
 PINK1
 PINK2
 PINK3
 RED1
 RED2
 RED4
 ROSYBROWN1
 ROSYBROWN2
 ROSYBROWN3
 ROSYBROWN4
 SEAGREEN
 SEAGREEN1
 SEAGREEN2
 SEAGREEN3
 SEAGREEN4
 SEASHELL1
 SEASHELL2
 SEASHELL3
 SEASHELL4
 SIENNA1
 SIENNA2
 SIENNA3
 SIENNA4
 SNOW
 SNOW2
 SNOW3
 SNOW4
 SPRINGGREEN
 STEELBLUE1
 STEELBLUE2
 STEELBLUE3
 STEELBLUE4
 TAN
 THISTLE4
 TRANSPARENT
 WHITESMOKE
 ALICEBLUE
 AZURE
 BISQUE3
 BISQUE4
 BURLYWOOD1
 BURLYWOOD2
 BURLYWOOD3
 BURLYWOOD4
 CHARTREUSE1
 CHARTREUSE2
 CHARTREUSE3
 CHARTREUSE4
 CHOCOLATE1
 CHOCOLATE2
 CHOCOLATE3
 CHOCOLATE4
 CORNSILK
 CORNSILK1
 DARKKHAKI
 DARKORANGE3
 DARKSLATEGRAY
 DARKSLATEGREY
 DEEPSKYBLUE4
 GOLD
 GOLDENROD
 GRAY
 GRAY10
 GRAY11
 GRAY12
 GRAY13
 GRAY14
 GRAY15
 GRAY41
 GRAY42
 GRAY43
 GRAY44
 GRAY45
 GRAY46
 GRAY47
 GRAY48
 GRAY7
 GRAY75
 GRAY76
 GRAY77
 GRAY78
 GRAY79
 GRAY8
 GRAY80
 GRAY81
 GRAY82
 GRAY9
 GREEN
 GREEN1
 GREEN2
 GREEN3
 GREEN4
 GREENYELLOW
 GREY10
 GREY11
 GREY12
 GREY13
 GREY14
 GREY40
 GREY41
 GREY42
 GREY43
 GREY44
 GREY45
 GREY46
 GREY47
 GREY48
 GREY7
 GREY74
 GREY75
 GREY76
 GREY77
 GREY78
 GREY79
 GREY8
 GREY80
 GREY81
 GREY82
 GREY9
 HONEYDEW
 INDIANRED
 IVORY
 KHAKI
 LAVENDER
 LAVENDERBLUSH
 LEMONCHIFFON
 LEMONCHIFFON1
 LEMONCHIFFON2
 LEMONCHIFFON3
 LEMONCHIFFON4
 LIGHTGOLDENROD
 LIGHTGOLDENRODYELLOW
 LIGHTPINK1
 LIGHTPINK2
 LIGHTPINK3
 LIGHTPINK4
 LIGHTSKYBLUE1
 LIGHTSKYBLUE2
 LIGHTSKYBLUE3
 LIGHTSKYBLUE4
 LIGHTSTEELBLUE1
 LIGHTSTEELBLUE2
 LIGHTYELLOW
 LIMEGREEN
 MAROON1
 MAROON2
 MAROON3
 MAROON4
 MEDIUMSPRINGGREEN
 MINTCREAM
 MISTYROSE
 MOCCASIN
 NAVAJOWHITE1
 NAVAJOWHITE2
 NAVAJOWHITE3
 NAVAJOWHITE4
 OLIVEDRAB
 OLIVEDRAB1
 OLIVEDRAB2
 OLIVEDRAB3
 PALEGOLDENROD
 PALEGREEN4
 PALEVIOLETRED1
 PALEVIOLETRED2
 PALEVIOLETRED3
 PALEVIOLETRED4
 PEACHPUFF1
 PEACHPUFF2
 PEACHPUFF3
 PEACHPUFF4
 PINK4
 RED
 SEASHELL
 SKYBLUE1
 SKYBLUE2
 SKYBLUE3
 SKYBLUE4
 SLATEGRAY1
 SLATEGRAY2
 SLATEGRAY3
 SLATEGRAY4
 SPRINGGREEN1
 SPRINGGREEN2
 SPRINGGREEN3
 SPRINGGREEN4
 TAN1
 TAN2
 TAN3
 TAN4
 VIOLETRED1
 VIOLETRED2
 VIOLETRED3
 WHEAT1
 WHEAT2
 WHEAT3
 WHEAT4
 WHITE
 YELLOWGREEN
 BEIGE
 BLACK
 BROWN
 BROWN1
 BROWN2
 BROWN3
 BROWN4
 BURLYWOOD
 CHOCOLATE
 CORNSILK2
 CORNSILK3
 CORNSILK4
 DARKOLIVEGREEN1
 DARKOLIVEGREEN2
 DARKOLIVEGREEN3
 DARKOLIVEGREEN4
 DARKSALMON
 DIMGRAY
 DIMGREY
 FIREBRICK1
 FIREBRICK2
 FIREBRICK3
 FIREBRICK4
 GRAY16
 GRAY17
 GRAY18
 GRAY19
 GRAY20
 GRAY49
 GRAY50
 GRAY51
 GRAY52
 GRAY53
 GRAY83
 GRAY84
 GRAY85
 GRAY86
 GRAY87
 GREY
 GREY15
 GREY16
 GREY17
 GREY18
 GREY19
 GREY49
 GREY50
 GREY51
 GREY52
 GREY53
 GREY83
 GREY84
 GREY85
 GREY86
 HONEYDEW1
 HONEYDEW2
 IVORY1
 IVORY2
 IVORY3
 IVORY4
 KHAKI1
 KHAKI2
 KHAKI3
 LIGHTBLUE1
 LIGHTBLUE2
 LIGHTBLUE3
 LIGHTBLUE4
 LIGHTCYAN1
 LIGHTCYAN2
 LIGHTCYAN3
 LIGHTGRAY
 LIGHTGREY
 LIGHTSLATEGRAY
 LIGHTSLATEGREY
 LIGHTSTEELBLUE3
 LIGHTSTEELBLUE4
 MAGENTA1
 MAGENTA2
 MAGENTA3
 MAGENTA4
 OLIVEDRAB4
 ORCHID1
 ORCHID2
 ORCHID3
 ORCHID4
 PERU
 RED3
 SADDLEBROWN
 SALMON
 SALMON1
 SALMON2
 SANDYBROWN
 SIENNA
 SLATEGRAY
 SLATEGREY
 VIOLETRED4
 WHEAT
 YELLOW
NIL|#



;;xxx
#|My FAVORITE COLORS in *my-main-colors-list1 ----------------------------------------
 ANTIQUEWHITE
 ANTIQUEWHITE2
 AQUAMARINE
 AQUAMARINE1
 AQUAMARINE2
 AQUAMARINE3
 AZURE1
 BLUE
 BLUE1
 BLUE2
 BLUE4
 CORAL
 CORAL3
 CYAN
 CYAN1
 DARK-BLUE
 DARKGOLDENROD1
 DARKGOLDENROD2
 DARKGOLDENROD4
 DARKOLIVEGREEN
 DARKORANGE
 DARKORANGE2
 DARKSEAGREEN
 DARKSEAGREEN1
 DARKSEAGREEN3
 DARKVIOLET
 DODGERBLUE1
 FIREBRICK
 FLORALWHITE
 FORESTGREEN
 GHOSTWHITE
 GOLD2
 GRAY0
 GRAY100
 GRAY21
 GRAY22
 GRAY32
 GRAY38
 GRAY4
 GRAY66
 GRAY67
 GREY100
 GREY32
 GREY33
 GREY36
 GREY59
 GREY65
 GREY66
 GREY71
 GREY99
 HIGHLIGHT-RED
 HOTPINK
 HOTPINK3
 INDIANRED1
 INDIANRED4
 LIGHT-BLUE
 LIGHT-BROWN
 LIGHT-RED
 LIGHTCYAN
 LIGHTGOLDENROD3
 LIGHTPINK
 LIGHTSALMON1
 LIGHTSALMON4
 LIGHTSKYBLUE
 LIGHTSTEELBLUE
 LIGHTYELLOW1
 MAGENTA
 MEDIUM-BLUE
 MEDIUMAQUAMARINE
 MEDIUMBLUE
 MEDIUMORCHID2
 MEDIUMPURPLE
 MEDIUMSEAGREEN
 MEDIUMTURQUOISE
 MIDNIGHTBLUE
 MISTYROSE1
 NAVY
 NAVYBLUE
 OLDLACE
 ORANGE
 ORANGE3
 ORANGERED
 ORANGERED3
 ORANGERED4
 ORCHID
 PLUM2
 PLUM4
 PURPLE3
 RED1
 ROSYBROWN
 ROSYBROWN2
 ROYALBLUE
 SALMON3
 SALMON4
 SEAGREEN3
 SEASHELL1
 SLATEBLUE
 SLATEBLUE1
 SNOW1
 SNOW2
 STEELBLUE
 STEELBLUE4
 TAN
 THISTLE
 THISTLE2
 THISTLE3
 TOMATO
 TURQUOISE
 VIOLET
 VIOLETRED
 WHITESMOKE
My FAVORITE COLORS in *my-main-colors-list2
 ALICEBLUE
 ANTIQUEWHITE3
 ANTIQUEWHITE4
 AZURE
 BEIGE
 BISQUE
 BISQUE1
 BISQUE2
 BISQUE3
 BISQUE4
 BLACK
 BLANCHEDALMOND
 BROWN1
 BROWN2
 BURLYWOOD
 BURLYWOOD1
 BURLYWOOD2
 BURLYWOOD3
 BURLYWOOD4
 CHARTREUSE
 CHARTREUSE1
 CHARTREUSE2
 CHARTREUSE3
 CHARTREUSE4
 CHOCOLATE
 CHOCOLATE1
 CHOCOLATE2
 CHOCOLATE3
 CHOCOLATE4
 CORNSILK
 CORNSILK1
 CORNSILK2
 CORNSILK3
 CORNSILK4
 DARKGREEN
 DARKKHAKI
 DARKOLIVEGREEN1
 DARKOLIVEGREEN2
 DARKOLIVEGREEN3
 DARKORANGE3
 DARKSALMON
 DARKSLATEGRAY
 DARKSLATEGREY
 DEEPSKYBLUE1
 DEEPSKYBLUE2
 DEEPSKYBLUE3
 DEEPSKYBLUE4
 DIMGRAY
 DIMGREY
 FIREBRICK1
 FIREBRICK2
 FIREBRICK3
 FIREBRICK4
 GOLD
 GOLDENROD
 GRAY
 GRAY10
 GRAY11
 GRAY12
 GRAY13
 GRAY14
 GRAY15
 GRAY16
 GRAY17
 GRAY18
 GRAY39
 GRAY40
 GRAY41
 GRAY42
 GRAY43
 GRAY44
 GRAY45
 GRAY46
 GRAY47
 GRAY48
 GRAY49
 GRAY5
 GRAY50
 GRAY51
 GRAY6
 GRAY7
 GRAY72
 GRAY73
 GRAY74
 GRAY75
 GRAY76
 GRAY77
 GRAY78
 GRAY79
 GRAY8
 GRAY80
 GRAY81
 GRAY82
 GRAY83
 GRAY84
 GRAY9
 GREEN
 GREEN1
 GREEN2
 GREEN3
 GREEN4
 GREENYELLOW
 GREY10
 GREY11
 GREY12
 GREY13
 GREY14
 GREY15
 GREY16
 GREY17
 GREY38
 GREY39
 GREY4
 GREY40
 GREY41
 GREY42
 GREY43
 GREY44
 GREY45
 GREY46
 GREY47
 GREY48
 GREY49
 GREY5
 GREY50
 GREY6
 GREY7
 GREY72
 GREY73
 GREY74
 GREY75
 GREY76
 GREY77
 GREY78
 GREY79
 GREY8
 GREY80
 GREY81
 GREY82
 GREY83
 GREY84
 GREY9
 HONEYDEW
 HOTPINK4
 INDIANRED
 IVORY
 IVORY1
 IVORY2
 IVORY3
 KHAKI
 LAVENDER
 LAVENDERBLUSH
 LAWNGREEN
 LEMONCHIFFON
 LEMONCHIFFON1
 LEMONCHIFFON2
 LEMONCHIFFON3
 LEMONCHIFFON4
 LIGHTBLUE1
 LIGHTBLUE2
 LIGHTBLUE3
 LIGHTGOLDENROD
 LIGHTGOLDENRODYELLOW
 LIGHTPINK1
 LIGHTPINK2
 LIGHTPINK3
 LIGHTPINK4
 LIGHTSEAGREEN
 LIGHTSKYBLUE1
 LIGHTSKYBLUE2
 LIGHTSKYBLUE3
 LIGHTSKYBLUE4
 LIGHTSLATEGRAY
 LIGHTSLATEGREY
 LIGHTSTEELBLUE1
 LIGHTSTEELBLUE2
 LIGHTSTEELBLUE3
 LIGHTSTEELBLUE4
 LIGHTYELLOW
 LIMEGREEN
 MAGENTA1
 MAGENTA2
 MAGENTA3
 MAROON1
 MAROON2
 MAROON3
 MAROON4
 MEDIUM-BROWN
 MEDIUM-GREEN
 MEDIUM-YELLOW
 MEDIUMSPRINGGREEN
 MINTCREAM
 MISTYROSE
 MOCCASIN
 NAVAJOWHITE
 NAVAJOWHITE1
 NAVAJOWHITE2
 NAVAJOWHITE3
 NAVAJOWHITE4
 OLIVEDRAB
 OLIVEDRAB1
 OLIVEDRAB2
 OLIVEDRAB3
 OLIVEDRAB4
 PALEGOLDENROD
 PALEGREEN
 PALEGREEN1
 PALEGREEN2
 PALEGREEN3
 PALEGREEN4
 PALEVIOLETRED1
 PALEVIOLETRED2
 PALEVIOLETRED3
 PALEVIOLETRED4
 PAPAYAWHIP
 PEACHPUFF
 PEACHPUFF1
 PEACHPUFF2
 PEACHPUFF3
 PEACHPUFF4
 PERU
 PINK1
 PINK2
 PINK3
 PINK4
 RED
 SADDLEBROWN
 SANDYBROWN
 SEAGREEN4
 SEASHELL
 SIENNA
 SIENNA1
 SIENNA2
 SIENNA3
 SIENNA4
 SKYBLUE1
 SKYBLUE2
 SKYBLUE3
 SKYBLUE4
 SLATEGRAY
 SLATEGRAY1
 SLATEGRAY2
 SLATEGRAY3
 SLATEGRAY4
 SLATEGREY
 SPRINGGREEN
 SPRINGGREEN1
 SPRINGGREEN2
 SPRINGGREEN3
 SPRINGGREEN4
 TAN1
 TAN2
 TAN3
 TAN4
 TRANSPARENT
 VIOLETRED1
 VIOLETRED2
 VIOLETRED3
 VIOLETRED4
 WHEAT
 WHEAT1
 WHEAT2
 WHEAT3
 WHEAT4
 WHITE
 YELLOW
 YELLOWGREEN
NIL|#

;;   (show-my-colors)
;;ddd
(defun show-my-colors ()
  "In U-colors.lisp, shows all my pre-selected LW colors with color names"
  (show-colors *my-main-colors-list1 "This is test text")
  (show-colors *my-main-colors-list2 "This is test text")
  )

;;  (show-all-colors)
;;ddd
(defun show-all-colors ()
  "In U-colors.lisp, shows all LW colors with color names"
  (show-colors *lw-colors-list1  "This is test text")
  (show-colors *lw-colors-list2  "This is test text")
  (show-colors *lw-colors-list3  "This is test text")
  (show-colors *lw-colors-list4  "This is test text")
  (show-colors *lw-colors-list5  "This is test text"))

;;
;;SAMPLE-COLORS
;;
;;ddd
(defun show-colors (color-list test-text)
  "In U-colors.lisp, shows color name, test-text, and a rectangle of each color from color-list"
  ;;first set the colors lists
  (lw-colors-list)

  ;;use global vars here
  (setf *temp-color-list color-list
        *temp-test-text test-text)
  (let
      ((instance (make-instance 'Color-Test-Interface))
       (cur-rectangle)
       (print-string)
       (x-test 10)
       (x-rect 30)
       (y-current 0)
       (i 0)
       )
    ;;display the instance
    (capi:display instance)
    ;;make color list of name, sample text, colored rectangle
    (dolist (color color-list)
      (incf i)
      (if  (or (= i 37)(= i 72))
          (setf y-current 0))

      ;;make columns
      (cond
       ((< i 36)
        (setf  x-text 10
               x-rect 220
               y-current (+ y-current 20)))
       ((and (>= i 36) (< i 72))
        (setf  x-text 350
               x-rect 550
               y-current (+ y-current 20)))
       ((>= i 72)
        (setf  x-text 700
               x-rect 950
               y-current (+ y-current 20))))       

      (with-slots (output-pane-1) instance
        (gp:draw-string output-pane-1 (format nil "~A" color) x-text y-current :foreground :black)
        (gp:draw-string output-pane-1 test-text (+ x-text 120) y-current :foreground color)
        (gp:draw-rectangle output-pane-1 x-rect (- y-current 15) 80 15 :filled t :foreground color)
        ))
    ))
        
 (capi:define-interface Color-Test-Interface ()
   ;;can't put doc here
   ;;"In U-colors.lisp, used for showing samples of  LW colors by color names"
    ()
    (:panes
     (output-pane-1
      capi:output-pane)
     (title-pane-1
      capi:title-pane
      :text "Color Test Window"))
    (:layouts
     (column-layout-1
      capi:column-layout
      '(output-pane-1 title-pane-1)))
    (:default-initargs
     :best-height 800
     :best-width 1100
     :scroll-vertical-page-size 800
     :vertical-scroll t
    :scroll-if-not-visible-p t
     :layout 'column-layout-1
     :iconify-callback 'redisplay-callback
     :title "Color-Test-Interface"))      

(defun redisplay-callback (data interface)
  (sample-colors *temp-color-list *temp-test-text))
      

;;xxx ------------------------------ MY (QUICKLY) SELECTED COLORS ---------------------------

;; FROM LIST USING (COLOR:GET-ALL-COLOR-NAMES)
;;
(defun my-colors-list ()
  "In U-colors, sets global *my-main-colors-list1 and *my-main-colors-list2"
  (setf *my-main-colors-list1
        `(:MAGENTA :SALMON3 :MIDNIGHTBLUE  :ORANGE3 :SALMON4 :PLUM2 :ORANGE :GRAY21 :NAVY :DARKORANGE :LIGHTSALMON1 :NAVYBLUE  :PLUM4 :LIGHTGOLDENROD3 :GRAY22 :CORAL :TOMATO :MEDIUMORCHID2 :LIGHTYELLOW1  :SLATEBLUE :LIGHTSALMON4 :MISTYROSE1 :ORANGERED  :HOTPINK :MEDIUMBLUE :ROYALBLUE :LIGHTPINK :AZURE1 :GREY59 :ROSYBROWN :DARKORANGE2 :CYAN1 :FIREBRICK :SLATEBLUE1 :LIGHTSKYBLUE :GOLD2 :VIOLETRED :CORAL3 :PURPLE3 :STEELBLUE :VIOLET :LIGHTSTEELBLUE  :DARKVIOLET :BLUE

          :DARKGOLDENROD1 :MEDIUMPURPLE :GREY65 :MEDIUMTURQUOISE :GRAY32 :THISTLE2 :ORANGERED3 :AQUAMARINE1 :BLUE1 :GREY99 :THISTLE :GRAY66 :DARKGOLDENROD2 :TURQUOISE :GREY32 :THISTLE3 :BLUE2 :ORANGERED4 :GRAY100 :AQUAMARINE2 :SNOW1 :GREY66 :CYAN :RED1 :GREY100 :AQUAMARINE3 :SNOW2 :GRAY67 :LIGHTCYAN :GREY33 :DARKGOLDENROD4 :GRAY0 :BLUE4 :LIGHT-RED :GHOSTWHITE :DARKSEAGREEN1 :ROSYBROWN2 :MEDIUMAQUAMARINE  :DODGERBLUE1  :SEASHELL1 :WHITESMOKE :HIGHLIGHT-RED :AQUAMARINE :TAN :LIGHT-BLUE :DARKSEAGREEN3
          :DARKOLIVEGREEN :FORESTGREEN :FLORALWHITE :MEDIUM-BLUE :INDIANRED1 :DARKSEAGREEN :GREY36 :OLDLACE :DARK-BLUE  :MEDIUMSEAGREEN :ANTIQUEWHITE :GRAY4 :LIGHT-BROWN :ANTIQUEWHITE2 :GREY71 :ORCHID :SEAGREEN3 :INDIANRED4 :GRAY38 :HOTPINK3 :STEELBLUE4 
          ))
  (setf *my-main-colors-list2
        '(
          :GREY4 :PAPAYAWHIP :LIGHTSEAGREEN :MEDIUM-BROWN :ANTIQUEWHITE3 :GRAY72 :SEAGREEN4 :SIENNA1 :GREY38 :HOTPINK4 :GRAY5 :DEEPSKYBLUE1 :PALEGREEN :BLANCHEDALMOND :GREY72 :MEDIUM-GREEN
          :ANTIQUEWHITE4 :SIENNA2 :PALEGREEN1 :GRAY39 :PINK1 :GREY5 :DEEPSKYBLUE2 :SPRINGGREEN :BISQUE :GRAY73 :BISQUE1 :SIENNA3 :GREY39 :MEDIUM-YELLOW :PALEGREEN2 :PINK2 :GRAY6 :LAWNGREEN :PEACHPUFF :GREY73 :DARKGREEN :DEEPSKYBLUE3 :BISQUE2 :SIENNA4 :GRAY40 :TRANSPARENT :PALEGREEN3 :PINK3 :GREY6 :GRAY74 :CHARTREUSE :NAVAJOWHITE :DARKORANGE3 :BISQUE3 :DEEPSKYBLUE4 :GREY40 :BURLYWOOD1 :PINK4 :PALEGREEN4 :GRAY7 :GREY74 :BISQUE4 :MOCCASIN :GRAY41 :SKYBLUE1 :MEDIUMSPRINGGREEN :BURLYWOOD2 :LIGHTPINK1 :GREY7 :SPRINGGREEN1 :GRAY75 :PEACHPUFF1 :CORNSILK :GREY41 :SKYBLUE2 :GREENYELLOW :BURLYWOOD3 :GRAY8 :LIGHTPINK2 :SPRINGGREEN2 :GREY75 :IVORY :GRAY42 :PEACHPUFF2 :GRAY :SKYBLUE3 :LIMEGREEN :GREY8 :BURLYWOOD4 :LIGHTPINK3 :GRAY76 :SPRINGGREEN3 :GREY42 :PEACHPUFF3 :LEMONCHIFFON :GRAY9 :SKYBLUE4 :YELLOWGREEN :WHEAT1 :LIGHTPINK4 :GREY76 :GRAY43 :SPRINGGREEN4 :PEACHPUFF4 :SEASHELL :GREY9 :WHEAT2 :OLIVEDRAB :LIGHTSKYBLUE1 :GRAY77 :PALEVIOLETRED1 :GREY43 :GREEN1 :GRAY10 :HONEYDEW :WHEAT3 :NAVAJOWHITE1 :DARKKHAKI :GREY77 :LIGHTSKYBLUE2 :PALEVIOLETRED2 :GRAY44 :GREEN2 :GREY10 :WHEAT4 :MINTCREAM :KHAKI :NAVAJOWHITE2 :GRAY78 :LIGHTSKYBLUE3 :GREY44 :GREEN3 :PALEVIOLETRED3 :GRAY11 :TAN1 :AZURE :GREY78 :GREEN :PALEGOLDENROD :NAVAJOWHITE3 :GRAY45 :GREEN4 :LIGHTSKYBLUE4 :GREY11 :TAN2 :PALEVIOLETRED4 :ALICEBLUE :GRAY79 :GREY45 :NAVAJOWHITE4 :CHARTREUSE1 :LIGHTGOLDENRODYELLOW :SLATEGRAY1 :GRAY12 :TAN3 :MAROON1 :LAVENDER :GREY79 :GRAY46 :CHARTREUSE2 :LEMONCHIFFON1 :LIGHTYELLOW :GREY12 :SLATEGRAY2 :TAN4 :MAROON2 :GRAY80 :LAVENDERBLUSH :GREY46 :GOLD :GRAY13 :CHARTREUSE3 :MAROON3 :SLATEGRAY3 :LEMONCHIFFON2 :CHOCOLATE1 :GREY80 :MISTYROSE :GRAY47 :GREY13 :MAROON4 :CHARTREUSE4 :LIGHTGOLDENROD :SLATEGRAY4 :CHOCOLATE2 :LEMONCHIFFON3 :GRAY81 :RED :WHITE :GREY47 :GRAY14 :VIOLETRED1 :OLIVEDRAB1 :GOLDENROD :CHOCOLATE3 :GREY81 :LIGHTSTEELBLUE1 :LEMONCHIFFON4 :GRAY48 :DARKSLATEGRAY :GREY14 :VIOLETRED2 :OLIVEDRAB2 :INDIANRED :GRAY82 :CHOCOLATE4 :LIGHTSTEELBLUE2 :CORNSILK1 :GREY48 :GRAY15 :DARKSLATEGREY :VIOLETRED3 :GREY82 :OLIVEDRAB3 :SADDLEBROWN :FIREBRICK1 :GRAY49 :CORNSILK2 :LIGHTSTEELBLUE3 :GREY15 :DIMGRAY :GRAY83 :SIENNA :VIOLETRED4 :OLIVEDRAB4 :FIREBRICK2 :GREY49 :CORNSILK3 :GRAY16 :LIGHTSTEELBLUE4 :DIMGREY :GREY83 :PERU :MAGENTA1 :GRAY50 :DARKOLIVEGREEN1 :FIREBRICK3 :CORNSILK4 :GREY16 :LIGHTBLUE1 :SLATEGRAY :GRAY84 :BURLYWOOD :MAGENTA2 :GREY50 :FIREBRICK4 :DARKOLIVEGREEN2 :IVORY1 :GRAY17 :LIGHTBLUE2 :SLATEGREY :GREY84 :BEIGE :GRAY51 :MAGENTA3 :BROWN1 :IVORY2 :GREY17 :DARKOLIVEGREEN3 :LIGHTBLUE3 :LIGHTSLATEGRAY :WHEAT :BROWN2 :IVORY3 :GRAY18  :SANDYBROWN :LIGHTSLATEGREY  :BLACK :CHOCOLATE :YELLOW :DARKSALMON))
  (format T "My FAVORITE COLORS in *my-main-colors-list1~%")
  (print-list *my-main-colors-list1 :sort-string-test #'string< :stream T ) 
  (format T "My FAVORITE COLORS in *my-main-colors-list2~%")
  (print-list *my-main-colors-list2  :sort-string-test #'string< :stream T ) 
  )

;;(sort *lw-colors-list1)
;; (sort '(a x 2))

;; XXX
;;xxx ------------------------------ ALL LISTWORKS COLOR NAMES  ---------------------------
;;             DIVIDED INTO 5 LISTS FOR DISPLAYING IN MY ABOVE FUNCTIONS

;;   TO SEE COLORS CALL my function (show-all-colors) above
;;

;; FROM LIST USING (COLOR:GET-ALL-COLOR-NAMES)
;;
;;CL-USER 3 > (color:get-all-color-names)

(defun lw-colors-list ()
  "In U-colors"
  (setf *lw-colors-list1 
        '(:HONEYDEW3 :KHAKI4 :GREY87 :GRAY54 :MAGENTA :LIGHTCYAN4 :SALMON3 :PLUM1 :LIGHTSALMON :GREY20 :MIDNIGHTBLUE :HONEYDEW4 :GRAY88 :LIGHTGOLDENROD1 :GREY54 :ORANGE3 :SALMON4 :PLUM2 :ORANGE :GRAY21 :NAVY :PALETURQUOISE1 :GREY88 :LAVENDERBLUSH1 :GRAY55 :LIGHTGOLDENROD2 :PLUM3 :GREY21 :DARKORANGE :LIGHTSALMON1 :NAVYBLUE :PALETURQUOISE2 :GRAY89 :GREY55 :LAVENDERBLUSH2 :PLUM4 :LIGHTGOLDENROD3 :GRAY22 :CORAL :LIGHTSALMON2 :CORNFLOWERBLUE :GREY89 :PALETURQUOISE3 :GRAY56 :LAVENDERBLUSH3 :GREY22 :MEDIUMORCHID1 :LIGHTGOLDENROD4 :LIGHTCORAL :GRAY90 :LIGHTSALMON3 :DARKSLATEBLUE :PALETURQUOISE4 :GREY56 :GRAY23 :LAVENDERBLUSH4 :TOMATO :MEDIUMORCHID2 :LIGHTYELLOW1 :GREY90 :SLATEBLUE :LIGHTSALMON4 :GRAY57 :CADETBLUE1 :GREY23 :MISTYROSE1 :ORANGERED :GRAY91 :MEDIUMORCHID3 :LIGHTYELLOW2 :ORANGE1 :GREY57 :CADETBLUE2 :MEDIUMSLATEBLUE :GRAY24 :HOTPINK :MISTYROSE2 :GREY91 :ORANGE2 :MEDIUMORCHID4 :GRAY58 :LIGHTYELLOW3 :CADETBLUE3 :GREY24 :LIGHTSLATEBLUE :DEEPPINK :GRAY92 :MISTYROSE3 :ORANGE4 :GREY58 :DARKORCHID1 :LIGHTYELLOW4 :GRAY25 :CADETBLUE4 :MEDIUMBLUE :PINK :GREY92 :MISTYROSE4 :GRAY59 :DARKORANGE1 :DARKORCHID2 :YELLOW1 :GREY25 :TURQUOISE1 :ROYALBLUE :GRAY93 :LIGHTPINK :AZURE1 :GREY59 :ROSYBROWN :DARKORANGE2 :YELLOW2))

  (setf *lw-colors-list2
        '( :DARKORCHID3 :GRAY26 :TURQUOISE2 :DODGERBLUE :GREY93 :AZURE2 :PALEVIOLETRED :GRAY60 :YELLOW3 :DARKORANGE4 :GREY26 :DARKORCHID4 :TURQUOISE3 :GRAY94 :DEEPSKYBLUE :AZURE3 :MAROON :GREY60 :YELLOW4 :CORAL1 :GRAY27 :PURPLE1 :GREY94 :TURQUOISE4 :SKYBLUE :AZURE4 :GRAY61 :MEDIUMVIOLETRED :GOLD1 :CORAL2 :GREY27 :PURPLE2 :GRAY95 :CYAN1 :FIREBRICK :SLATEBLUE1 :LIGHTSKYBLUE :GREY61 :GOLD2 :VIOLETRED :CORAL3 :GRAY28 :PURPLE3 :GREY95 :CYAN2 :GRAY62 :SLATEBLUE2 :STEELBLUE :GOLD3 :VIOLET :CORAL4 :GREY28 :PURPLE4 :GRAY96 :CYAN3 :GREY62 :SLATEBLUE3 :GOLD4 :PLUM :LIGHTSTEELBLUE :TOMATO1 :GRAY29 :MEDIUMPURPLE1 :GREY96 :CYAN4 :GRAY63 :SLATEBLUE4 :TOMATO2 :GREY29 :GOLDENROD1 :LIGHTBLUE :MEDIUMORCHID :GRAY97 :MEDIUMPURPLE2 :PURPLE :DARKSLATEGRAY1 :GREY63 :TOMATO3 :GRAY30 :ROYALBLUE1 :GOLDENROD2 :POWDERBLUE :DARKORCHID :GREY97 :MEDIUMPURPLE3 :GRAY64 :DARKSLATEGRAY2 :TOMATO4 :GREY30 :ROYALBLUE2 :GOLDENROD3 :DARKVIOLET :PALETURQUOISE :GRAY98 :GREY64 :MEDIUMPURPLE4 :GRAY31 :DARKSLATEGRAY3 :ORANGERED1 :ROYALBLUE3 :GOLDENROD4 :GREY98 :BLUEVIOLET :DARKTURQUOISE :GRAY65 :THISTLE1 :GREY31 :ORANGERED2 :DARKSLATEGRAY4 :ROYALBLUE4 :GRAY99 :BLUE :DARKGOLDENROD1 :MEDIUMPURPLE :GREY65 :MEDIUMTURQUOISE :GRAY32 :THISTLE2 :ORANGERED3 :AQUAMARINE1 :BLUE1 :GREY99 :THISTLE :GRAY66 :DARKGOLDENROD2 :TURQUOISE :GREY32 :THISTLE3 :BLUE2 :ORANGERED4 :GRAY100 :AQUAMARINE2 :SNOW1 :GREY66))

  (setf *lw-colors-list3
        '(:CYAN :DARKGOLDENROD3 :GRAY33 :THISTLE4 :BLUE3 :RED1 :GREY100 :AQUAMARINE3 :SNOW2 :GRAY67 :LIGHTCYAN :GREY33 :DARKGOLDENROD4 :GRAY0 :BLUE4 :RED2 :LISPWORKS-BLUE :AQUAMARINE4 :SNOW3 :SNOW :GREY67 :DARKGOLDENROD :GRAY34 :CADETBLUE :ROSYBROWN1 :GREY0 :RED4 :DODGERBLUE1 :SNOW4 :GRAY68 :LIGHT-RED :GHOSTWHITE :DARKSEAGREEN1 :GREY34 :GRAY1 :ROSYBROWN2 :MEDIUMAQUAMARINE :DEEPPINK1 :DODGERBLUE2 :GREY68 :SEASHELL1 :WHITESMOKE :HIGHLIGHT-RED :GRAY35 :DARKSEAGREEN2 :GREY1 :ROSYBROWN3 :AQUAMARINE :DEEPPINK2 :DODGERBLUE3 :GRAY69 :TAN :SEASHELL2 :GAINSBORO :GREY35 :LIGHT-BLUE :DARKSEAGREEN3  :ROSYBROWN4 :DARKOLIVEGREEN :DEEPPINK3 :GREY69 :DODGERBLUE4 :SEASHELL3 :GRAY36 :FORESTGREEN :FLORALWHITE :MEDIUM-BLUE :GREY2 :DARKSEAGREEN4 :INDIANRED1 :GRAY70 :DEEPPINK4 :STEELBLUE1 :DARKSEAGREEN :GREY36 :SEASHELL4 :OLDLACE :DARK-BLUE :GRAY3 :SEAGREEN1 :GREY70 :INDIANRED2 :HOTPINK1 :STEELBLUE2 :SEAGREEN :GRAY37 :LINEN :ANTIQUEWHITE1 :GREY3 :GRAY-BLUE :SEAGREEN2 :GRAY71 :INDIANRED3 :HOTPINK2 :GREY37 :STEELBLUE3 :MEDIUMSEAGREEN :ANTIQUEWHITE :GRAY4 :LIGHT-BROWN :ANTIQUEWHITE2 :GREY71 :ORCHID :SEAGREEN3 :INDIANRED4 :GRAY38 :HOTPINK3 :STEELBLUE4 :GREY4 :PAPAYAWHIP :LIGHTSEAGREEN :MEDIUM-BROWN :ANTIQUEWHITE3 :GRAY72 :SEAGREEN4 :SIENNA1 :GREY38 :HOTPINK4 :GRAY5 :DEEPSKYBLUE1 :PALEGREEN :BLANCHEDALMOND :GREY72 :MEDIUM-GREEN :ANTIQUEWHITE4 :SIENNA2 :PALEGREEN1 :GRAY39 :PINK1 :GREY5 :DEEPSKYBLUE2 :SPRINGGREEN :BISQUE :GRAY73 :BISQUE1 :SIENNA3 :GREY39 :MEDIUM-YELLOW :PALEGREEN2 :PINK2 :GRAY6 :LAWNGREEN :PEACHPUFF :GREY73 :DARKGREEN :DEEPSKYBLUE3 :BISQUE2 :SIENNA4 :GRAY40 :TRANSPARENT :PALEGREEN3 :PINK3 :GREY6 :GRAY74 :CHARTREUSE :NAVAJOWHITE))

  (setf *lw-colors-list4 
        '( :DARKORANGE3 :BISQUE3 :DEEPSKYBLUE4 :GREY40 :BURLYWOOD1 :PINK4 :PALEGREEN4 :GRAY7 :GREY74 :BISQUE4 :MOCCASIN :GRAY41 :SKYBLUE1 :MEDIUMSPRINGGREEN :BURLYWOOD2 :LIGHTPINK1 :GREY7 :SPRINGGREEN1 :GRAY75 :PEACHPUFF1 :CORNSILK :GREY41 :SKYBLUE2 :GREENYELLOW :BURLYWOOD3 :GRAY8 :LIGHTPINK2 :SPRINGGREEN2 :GREY75 :IVORY :GRAY42 :PEACHPUFF2 :GRAY :SKYBLUE3 :LIMEGREEN :GREY8 :BURLYWOOD4 :LIGHTPINK3 :GRAY76 :SPRINGGREEN3 :GREY42 :PEACHPUFF3 :LEMONCHIFFON :GRAY9 :SKYBLUE4 :YELLOWGREEN :WHEAT1 :LIGHTPINK4 :GREY76 :GRAY43 :SPRINGGREEN4 :PEACHPUFF4 :SEASHELL :GREY9 :WHEAT2 :OLIVEDRAB :LIGHTSKYBLUE1 :GRAY77 :PALEVIOLETRED1 :GREY43 :GREEN1 :GRAY10 :HONEYDEW :WHEAT3 :NAVAJOWHITE1 :DARKKHAKI :GREY77 :LIGHTSKYBLUE2 :PALEVIOLETRED2 :GRAY44 :GREEN2 :GREY10 :WHEAT4 :MINTCREAM :KHAKI :NAVAJOWHITE2 :GRAY78 :LIGHTSKYBLUE3 :GREY44 :GREEN3 :PALEVIOLETRED3 :GRAY11 :TAN1 :AZURE :GREY78 :GREEN :PALEGOLDENROD :NAVAJOWHITE3 :GRAY45 :GREEN4 :LIGHTSKYBLUE4 :GREY11 :TAN2 :PALEVIOLETRED4 :ALICEBLUE :GRAY79 :GREY45 :NAVAJOWHITE4 :CHARTREUSE1 :LIGHTGOLDENRODYELLOW :SLATEGRAY1 :GRAY12 :TAN3 :MAROON1 :LAVENDER :GREY79 :GRAY46 :CHARTREUSE2 :LEMONCHIFFON1 :LIGHTYELLOW :GREY12 :SLATEGRAY2 :TAN4 :MAROON2 :GRAY80 :LAVENDERBLUSH :GREY46 :GOLD :GRAY13 :CHARTREUSE3 :MAROON3 :SLATEGRAY3 :LEMONCHIFFON2 :CHOCOLATE1 :GREY80 :MISTYROSE :GRAY47 :GREY13 :MAROON4 :CHARTREUSE4 :LIGHTGOLDENROD :SLATEGRAY4 :CHOCOLATE2 :LEMONCHIFFON3 :GRAY81 :RED :WHITE :GREY47 :GRAY14 :VIOLETRED1 :OLIVEDRAB1 :GOLDENROD :CHOCOLATE3 :GREY81 :LIGHTSTEELBLUE1 :LEMONCHIFFON4 :GRAY48 :DARKSLATEGRAY :GREY14 :VIOLETRED2 :OLIVEDRAB2 :INDIANRED :GRAY82 :CHOCOLATE4 :LIGHTSTEELBLUE2 :CORNSILK1 :GREY48 :GRAY15 :DARKSLATEGREY :VIOLETRED3 :GREY82 :OLIVEDRAB3)
        )

  (setf *lw-colors-list5
        '( :SADDLEBROWN :FIREBRICK1 :GRAY49 :CORNSILK2 :LIGHTSTEELBLUE3 :GREY15 :DIMGRAY :GRAY83 :SIENNA :VIOLETRED4 :OLIVEDRAB4 :FIREBRICK2 :GREY49 :CORNSILK3 :GRAY16 :LIGHTSTEELBLUE4 :DIMGREY :GREY83 :PERU :MAGENTA1 :GRAY50 :DARKOLIVEGREEN1 :FIREBRICK3 :CORNSILK4 :GREY16 :LIGHTBLUE1 :SLATEGRAY :GRAY84 :BURLYWOOD :MAGENTA2 :GREY50 :FIREBRICK4 :DARKOLIVEGREEN2 :IVORY1 :GRAY17 :LIGHTBLUE2 :SLATEGREY :GREY84 :BEIGE :GRAY51 :MAGENTA3 :BROWN1 :IVORY2 :GREY17 :DARKOLIVEGREEN3 :LIGHTBLUE3 :GRAY85 :LIGHTSLATEGRAY :WHEAT :GREY51 :BROWN2 :MAGENTA4 :IVORY3 :GRAY18 :DARKOLIVEGREEN4 :GREY85 :LIGHTBLUE4 :SANDYBROWN :LIGHTSLATEGREY :GRAY52 :BLACK :BROWN3 :ORCHID1 :IVORY4 :GREY18 :BROWN :KHAKI1 :GRAY86 :LIGHTCYAN1 :GREY :GREY52 :CHOCOLATE :BROWN4 :ORCHID2 :GRAY19 :HONEYDEW1 :YELLOW :KHAKI2 :GREY86 :RED3 :LIGHTCYAN2 :GRAY53 :LIGHTGREY :DARKSALMON :SALMON1 :ORCHID3 :GREY19 :HONEYDEW2 :KHAKI3 :GRAY87 :GREY53 :LIGHTCYAN3 :SALMON :LIGHTGRAY :SALMON2 :ORCHID4 :GRAY20))
  (format T "ListWorks Colors ---------------------------------------- ~%")
  (print-list *lw-colors-list1  :sort-string-test #'string< :stream T ) 
  (print-list *lw-colors-list2 :sort-string-test #'string< :stream T ) 
  (print-list *lw-colors-list3  :sort-string-test #'string< :stream T ) 
  (print-list *lw-colors-list4 :sort-string-test #'string< :stream T ) 
  (print-list *lw-colors-list5  :sort-string-test #'string< :stream T ) 
  )

